on: [push]
name: Auth build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Go mod
        working-directory: ./auth
        run: go mod download
      - name: Build
        working-directory: ./auth
        run: go build ./cmd/main.go
      - name: Run tests
        working-directory: ./auth
        run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./auth
          version: v1.59
          args: --config=./auth/.golangci.pipeline.yml